module.exports = {
    'env': {
        'node': true,
        'es6': true
    },
    'extends': 'eslint:recommended',
    'parser': 'babel-eslint',
    'rules': {
        'for-directions': true,
        'no-dupe-keys': 2,
        'no-duplicate-case': 2,
        'no-invalid-regexp': 2,
        'no-irregular-whitespace': 2,
        'no-regex-spaces': 2,
        'no-unreachable': 2,
        'curly': 2,
        'default-case': 2,
        'dot-location': ["error", "property"],
        'eqeqeq': 2,
        'no-empty-function': 2,
        'no-fallthrough': 2,
        'no-multi-spaces': 0,
        'no-proto': 2,
        'no-unused-expressions': 2,
        'no-useless-return': 2,
        'strict': 2,
        'no-label-var': 2,
        'no-undefined': 2,
        'no-use-before-define': 2,
        'camelcase': 2,
        'comma-dangle': 0,
        'indent': ["error", 2],
        'key-spacing': 1,
        'no-mixed-spaces-and-tabs': 2,
        'no-duplicate-imports': 2,
        'no-var': 2,
        'prefer-const': 0,
        'no-shadow': 2,
    }
};